### ISSUE TITLE
No joy with Asuswrt-Merlin 380.68 

### ISSUE THREAD

**Issue by veganvelociraptor** [kvic-z/goodies-asuswrt#1]
Apparently, some update was made to the menuTree API, making it incompatible with this ntpd. Thus, the instructions on how to install ntpd no longer work either.

**Comment by kvic-z** [comment]
thanks for your feedback. Seems others run into the same issue on FW >= 380.68.

Updated Step 5 for FW >=380.68 from input of [Martineau@snbforums](https://www.snbforums.com/threads/ntp-daemon-for-asuswrt-merlin.28041/page-18#post-342620)
